const data = {
    products: [
        {
            _id: '1',
            name: 'Nike everyday sneakers',
            category: 'Shoes',
            image: '/images/shoes/shoes1.jpeg',
            price: 80,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Superstar',
            category: 'Shoes',
            image: '/images/shoes/shoes2.jpeg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lacoste textile shoes',
            category: 'Shoes',
            image: '/images/shoes/shoes3.jpg',
            price: 50,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 16,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Gardion suit shoes',
            category: 'Shoes',
            image: '/images/shoes/shoes4.jpeg',
            price: 135,
            brand: 'Gardion',
            rating: 4.2,
            numReviews: 13,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nike OG shoes',
            category: 'Shoes',
            image: '/images/shoes/shoes5.jpeg',
            price: 110,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 18,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Guantimo summer shoes',
            category: 'Shoes',
            image: '/images/shoes/shoes6.jpeg',
            price: 142,
            brand: 'Guantimo',
            rating: 4.7,
            numReviews: 22,
            description: 'high quality product',
        },
    ],
}

export default data
